jobs:
  - ${{ each image in parameters.image }}:
    - ${{ each concurrency_level in parameters.concurrency_level }}:
      - ${{ each security in parameters.security }}:
        - job: 
          displayName: ${{ image }}_${{ concurrency_level }}_${{ security }}
          pool:
            vmImage: ${{ image }}
          steps:
            - task: Bash@3
              inputs:
                filePath: 'build.sh'
                arguments: '-Fx net5'          