jobs:
  - ${{ each image in parameters.image }}:
    - ${{ each concurrency_level in parameters.concurrency_level }}:
      - ${{ each security in parameters.security }}:
        - job: 
          displayName: ${{ image }}_${{ concurrency_level }}_${{ security }}
          pool:
            vmImage: ${{ image }}
          steps:
            - script: dotnet test --configuration:Release test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f netcoreapp3.1
              env:
                TRANSPORT_SECURITY: ${{ security }}